# Site settings
title: nearly functional
#email: your-email@domain.com
description: >
  Articles on systems engineering, software development, and scalable data
  stores. Opinions expressed are solely my own and do not express the views
  or opinions of my employer.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://wildflame.me" # the base hostname & protocol for your site
twitter_username: opeckojo
github_username:  jopecko

# Build settings
markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-paginate-v2
  - jekyll-relative-links
  - jekyll-last-modified-at

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

defaults:
  - scope:
      path: "_snippets"
    values:
      layout: snippet
      nav_id: /snippets/
      has_contributions: true
      author: jopecko

collections:
  snippets:
    relative_directory: "_snippets"
    output: true

pagination:
  enabled: true
  per_page: 20
  permalink: "/page/:num"
  title: ":title - page :num"
  sort_reverse: true

navigation:
  - title: snippets
    url: /snippets/
    id: /snippets/

authors:
  jopecko:
    name: Joe O'Pecko
    github: jopecko
    twitter: opeckojo